# Generated by Django 2.2.3 on 2020-10-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemonentity",
            name="defence",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pokemonentity",
            name="health",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pokemonentity",
            name="level",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pokemonentity",
            name="stamina",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pokemonentity",
            name="strength",
            field=models.IntegerField(default=0),
        ),
    ]
