# Generated by Django 2.2.3 on 2020-10-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0002_auto_20201009_0028"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pokemon",
            name="title",
        ),
        migrations.AddField(
            model_name="pokemon",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="title_en",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="title_jp",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="title_ru",
            field=models.CharField(default="", max_length=200),
        ),
    ]
