# Generated by Django 2.2.3 on 2020-10-10 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0004_auto_20201010_0142"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="next_evolution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="next",
                to="pokemon_entities.Pokemon",
                verbose_name="потомок",
            ),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="previous_evolution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="previous",
                to="pokemon_entities.Pokemon",
                verbose_name="предок",
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="pokemon",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pokemon_entities.Pokemon",
                verbose_name="покемон",
            ),
        ),
    ]
