# Generated by Django 2.2.3 on 2020-10-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0016_auto_20201017_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./images/thumbs', verbose_name='Изображение'),
        ),
    ]
